### ISSUE TITLE
DNS lookups fail

### ISSUE THREAD

**Issue by regnete** [juanluisbaptiste/docker-postfix#51]
docker-compose yml
```
services:
  smtp:
    image: juanluisbaptiste/postfix
    environment:
      SERVER_HOSTNAME: "xxx"
      SMTP_SERVER: 'smtp.mydomain.intranet'
      SMTP_PORT: '587'
      SMTP_USERNAME: 'someuser'
      SMTP_PASSWORD: "secret"
    extra_hosts:
      - "smtp.mydomain.intranet:192.168.5.1"
```

**Describe the issue**
postfix cannot resolve the host smtp.mydomain.intranet
I guess this happens due to the issue decribed here: https://serverfault.com/a/1004330

**Expected behavior**
postfix resolves the host smtp.mydomain.intranet to 192.168.5.1
